name: Pipeline

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build_job:
    runs-on: ubuntu-latest
    container:
      image: kselyunin/python3.9-sphinx-rtd:v0.1
    env:
      VERSION_MAJOR: 0
      VERSION_MINOR: 0
      DOCS_VERSION: 0.0.0
      PROJECT: rsl_sphinx_docs

    steps:
      - uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}

      - uses: actions/checkout@v2
        with:
          repository: selyunin/app3.0_docs
          path: 'app30_docs_src'
          ref: ''
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Read version number
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        run: |
          VERSION_MAJOR=`sed -n '1p' app30_docs_src/VERSION | grep -oEi ":.*" | grep -oEi "[[:alnum:]]+"`
          VERSION_MINOR=`sed -n '2p' app30_docs_src/VERSION | grep -oEi ":.*" | grep -oEi "[[:alnum:]]+"`
          DOCS_VERSION=${MAJOR}.${MINOR}.${BUILD_NUMBER}
          echo "VERSION_MAJOR=${VERSION_MAJOR}" >> $GITHUB_ENV
          echo "VERSION_MINOR=${VERSION_MINOR}" >> $GITHUB_ENV
          echo "DOCS_VERSION=${VERSION_MAJOR}.${VERSION_MINOR}.${BUILD_NUMBER}" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Build documentation
        shell: bash
        run: |
          ls -la .
          pwd
          ls -la app30_docs_src
          cd app30_docs_src && sphinx-build -b html source build/html

      - name: Update generated HTML files
        shell: bash
        run: |
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          cd ${GITHUB_WORKSPACE}
          pwd
          ls -la .
          mkdir -pv app30_docs_src/docs/
          cp -r app30_docs_src/build/html/* app30_docs_src/docs
          touch app30_docs_src/docs/.nojekyll
          ls -la app30_docs_src/docs/

      - name: Deploy to GitHub actions
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: app30_docs_src/docs/ # The folder the action should deploy.
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commit-message: 'v${{ env.DOCS_VERSION }} --force'


